### ISSUE TITLE
Add config option for passing bootstrap server(s)

### ISSUE THREAD

**Issue by dkvasnicka** [sauljabin/kaskade#16]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to run `kaskade` in k8s because I can't just pass it the boostrap servers instead of fiddling with volumes and config files

**Describe the solution you'd like**
A CLI config option to pass in a `hostname:port` bootstrap server

**Comment by dkvasnicka** [comment]
Current workaround is to use `kcli` (which, btw, also nicely auto-formats the JSON payload in a Kafka msg ;) ).

**Comment by sauljabin** [comment]
Hi thanks, working on it, I'm preparing v2

**Comment by sauljabin** [comment]
Hello @dkvasnicka thanks for helping me to improve kaskade, would you mind to install the newest version?, let me know your feedback

- fixed on v2
