### ISSUE TITLE
Failed to get committed offsets: Local: Unknown group

### ISSUE THREAD

**Issue by exoodo** [sauljabin/kaskade#4]
**Describe the bug**
When i try to start kaskade shows an error:

`🤔 A problem has occurred "Failed to get committed offsets: Local: Unknown group"`

**To Reproduce**

my kaskade.yml is like this:

> kafka:
>   bootstrap.servers: SERVER
>   security.protocol: SASL_SSL
>   sasl.mechanisms: PLAIN
>   sasl.username: SASL_USERNAME
>   sasl.password: SASL_PASSWORD
>   session.timeout.ms: 45000
> kaskade:
>   debug: on

**Expected behavior**
 Kaskade does not start

**Desktop (please complete the following information):**
docker run --rm -it --network kafka \
--volume $(pwd):/kaskade \
sauljabin/kaskade:latest

**Additional context**
 I am trying connect to confluent cloud cluster

**Comment by sauljabin** [comment]
Hi @exoodo would you mind to elaborate a little more?
